SELECT
*
FROM 
INDEXANALYSIS..NIFTY_50
Where
High is NOT NULL

--removing column which are not needed
ALTER table
IndexAnalysis..NIFTY_50
DROP COLUMN
"close"

-- for finding daily return of nifty_50 
Select 
High,Date,Newclose,(newclose/Lag(newclose,1)
over( ORDER BY date)-1)*100 As "Daily_return" 
FROM
IndexAnalysis..NIFTY_50
ORDER BY DATE 


-- USING CTE FOR VISUALISING DAILY RETURN VIEW FOR NIFTY FOR 5 YEARS 


WITH
ASDAILY
(
Date, HIGH,Newclose,Daily_return
)
AS
(
Select 
High,Date,Newclose,(newclose/Lag(newclose,1)
over( ORDER BY date)-1)*100 As "Daily_return" 
FROM
IndexAnalysis..NIFTY_50 
--ORDER BY DATE
)
SELECT
(Daily_return) 
FROM
ASDAILY

--USING CTE FOR FINDING OUT STANDARD DEVIATION FOR THE INDEX
WITH
STD_DEV
(
Date, HIGH,Newclose,Daily_return
)
AS
(
Select 
High,Date,Newclose,(newclose/Lag(newclose,1)
over( ORDER BY date)-1)*100 As "Daily_return" 
FROM
IndexAnalysis..NIFTY_50 
--ORDER BY DATE
)
SELECT
(AVG(Daily_return) +STDEV(Daily_return)) AS ONE_SD,
(AVG(Daily_return) -STDEV(Daily_return)) AS NEG_ONE_SD,
(AVG(Daily_return) +2*(STDEV(Daily_return))) AS TWO_SD,
(AVG(Daily_return) -2*(STDEV(Daily_return))) AS NEG_TWO_SD,
(AVG(Daily_return) +3*STDEV(Daily_return)) AS THREE_SD,
(AVG(Daily_return) -3*STDEV(Daily_return)) AS NEG_THREE_SD
FROM
STD_DEV


--NOW COMBINING COLUMN FOR +/- STDEV
--FOR THIS WE WILL USE TEMP TABLE METHOD

--AS WE JUST GOT TO KNOW WE CANNOT USE CTE TABLE IN ANOTHER PROCESSES SO WE WILL MAKE TEMP TABLE TO WORK BELOW QUERY
--DROP TABLE IF EXISTS STANDARD_DEVIATION_INFO
--CREATE TABLE STANDARD_DEVIATION_INFO
--(
--ONE_STDDEV FLOAT,
--TWO_STDDEV FLOAT,
--THREE_STDDEV FLOAT
--)
--INSERT INTO STANDARD_DEVIATION_INFO

--SELECT
--CONCAT(ONE_SD,'/',NEG_ONE_SD),
--CONCAT(TWO_SD,'/',NEG_TWO_SD),
--CONCAT(THREE_SD,'/',NEG_THREE_SD)
--FROM
--STD_DEV

--SELECT *
--FROM STANDARD_DEVIATION_INFO

SELECT
*
FROM
IndexAnalysis..NIFTY_50
ORDER BY DATE ASC

--NOW WE WILL ANALYSE ONE MORE MAJOR INDEX NIFTYBANK AND JOIN TWO ABLES FOR MORE INFORMATION
SELECT 
*
FROM
IndexAnalysis..niftybank

--- REMOVING DATA WE DO NOT NEED
ALTER TABLE
INDEXANALYSIS..NIFTYBANK
DROP COLUMN
VOLUME

ALTER TABLE
INDEXANALYSIS..NIFTYBANK
DROP COLUMN
"Close"

SELECT
*
FROM
IndexAnalysis..NIFTYBANK

--FINDING DAILY RETURN FOR BANNIFTY

SELECT
NI_DATE,NI_Newclose,
((NI_Newclose/LAG(NI_Newclose,1) OVER(ORDER BY NI_DATE)-1))*100 AS DAILYRETURN
FROM
IndexAnalysis..NIFTYBANK

Select 
*
FROM
IndexAnalysis..NIFTY_50 NI
join
IndexAnalysis..NIFTYBANK NB
ON
NI.DATE=NB.DATE

--NOW WE WILL USE CTE FOR PLACING STANDARD DEVIATION OF BOTH THE INDEX IN ONE TABLE::
--FIRST COMBINING DAILY RETUNRS FOR BOTH THE INDEXES
WITH 
COMBINE_INFO
(
Date,Daily_return_NIFTY50,Daily_return_BANKNIFTY
)
AS
(
Select
DATE,
((Newclose/LAG(Newclose,1) OVER(ORDER BY DATE)-1))*100 ,
((NI_Newclose/LAG(NI_Newclose,1) OVER(ORDER BY NI_DATE)-1))*100 
FROM
IndexAnalysis..NIFTY_50 NI
join
IndexAnalysis..NIFTYBANK NB
ON
NI.DATE=NB.NI_DATE
--ORDER BY DATE
)
--COMBINING THE STANDARD DEVIATION DATA FOR BOTH THE INDEXES
SELECT
(AVG(Daily_return_NIFTY50) +STDEV(Daily_return_NIFTY50)) AS ONE_SD,
(AVG(Daily_return_NIFTY50) -STDEV(Daily_return_NIFTY50)) AS NEG_ONE_SD,
(AVG(Daily_return_NIFTY50) +2*(STDEV(Daily_return_NIFTY50))) AS TWO_SD,
(AVG(Daily_return_NIFTY50) -2*(STDEV(Daily_return_NIFTY50))) AS NEG_TWO_SD,
(AVG(Daily_return_NIFTY50) +3*STDEV(Daily_return_NIFTY50)) AS THREE_SD,
(AVG(Daily_return_NIFTY50) -3*STDEV(Daily_return_NIFTY50)) AS NEG_THREE_SD,
(AVG(Daily_return_BANKNIFTY) +STDEV(Daily_return_BANKNIFTY)) AS NB_ONE_SD,
(AVG(Daily_return_BANKNIFTY) -STDEV(Daily_return_BANKNIFTY)) AS NB_NEG_ONE_SD,
(AVG(Daily_return_BANKNIFTY) +2*(STDEV(Daily_return_BANKNIFTY))) AS NB_TWO_SD,
(AVG(Daily_return_BANKNIFTY) -2*(STDEV(Daily_return_BANKNIFTY))) AS NB_NEG_TWO_SD,
(AVG(Daily_return_BANKNIFTY) +3*STDEV(Daily_return_BANKNIFTY)) AS NB_THREE_SD,
(AVG(Daily_return_BANKNIFTY) -3*STDEV(Daily_return_BANKNIFTY)) AS NB_NEG_THREE_SD
FROM
COMBINE_INFO


--ALWAYS REMEMBER WHILE CREATING VIEW ALWAYS ASSIGN ALIAS TO THE COLUMN WHICH HAS MULTIPLE COLUMNS IN IT AS CALCULATIONS
CREATE View functional
AS
Select
((Newclose/LAG(Newclose,1) OVER(ORDER BY DATE)-1))*100 AS NIFTY_DAILY_RETURN ,
((NI_Newclose/LAG(NI_Newclose,1) OVER(ORDER BY NI_DATE)-1))*100 AS BANKNIFTY_DAILY_RETURN
FROM
IndexAnalysis..NIFTY_50 NI
join
IndexAnalysis..NIFTYBANK NB
ON
NI.DATE=NB.NI_DATE

DROP VIEW FUNCTIONAL
--ORDER BY DATE

--AS WE HAVE TO TRANSPOSE THE RESULT SO IT CAN BE MORE EPRESENTABLE , FOR THAT WE WILL MAKE A TEMP-TABLE::
DROP TABLE IF EXISTS SUMMARY_RESULTS
CREATE TABLE
SUMMARY_RESULTS
(
NSE50_ONE_SD FLOAT,
NSE50_NEG_ONE_SD FLOAT,
NSE50_TWO_SD FLOAT,
NSE50_NEG_TWO_SD FLOAT,
NSE50_THREE_SD FLOAT,
NSE50_NEG_THREE_SD FLOAT,
NSEBANK_ONE_SD FLOAT,
NSEBANK_NEG_ONE_SD FLOAT,
NSEBANK_TWO_SD FLOAT,
NSEBANK_NEG_TWO_SD FLOAT,
NSEBANK_THREE_SD FLOAT,
NSEBANK_NEG_THREE_SD FLOAT,

)
INSERT INTO SUMMARY_RESULTS
Select
(((NI.Newclose/LAG(NI.Newclose,1) OVER(ORDER BY NI.DATE)-1))*100+STDEV((NI.Newclose/LAG(NI.Newclose,1) OVER(ORDER BY NI.DATE)-1)*100)),
(((NI.Newclose/LAG(NI.Newclose,1) OVER(ORDER BY NI.DATE)-1))*100-STDEV((NI.Newclose/LAG(NI.Newclose,1) OVER(ORDER BY NI.DATE)-1)*100)),
(((NI.Newclose/LAG(NI.Newclose,1) OVER(ORDER BY NI.DATE)-1))*100+2*(STDEV((NI.Newclose/LAG(NI.Newclose,1) OVER(ORDER BY NI.DATE)-1)*100))),
(((NI.Newclose/LAG(NI.Newclose,1) OVER(ORDER BY NI.DATE)-1))*100-2*(STDEV((NI.Newclose/LAG(NI.Newclose,1) OVER(ORDER BY NI.DATE)-1)*100))),
(((NI.Newclose/LAG(NI.Newclose,1) OVER(ORDER BY NI.DATE)-1))*100+3*(STDEV((NI.Newclose/LAG(NI.Newclose,1) OVER(ORDER BY NI.DATE)-1)*100))),
(((NI.Newclose/LAG(NI.Newclose,1) OVER(ORDER BY NI.DATE)-1))*100-3*(STDEV((NI.Newclose/LAG(NI.Newclose,1) OVER(ORDER BY NI.DATE)-1)*100))),
(((NB.NI_Newclose/LAG(NB.NI_Newclose,1) OVER(ORDER BY NB.NI_DATE)-1))*100+STDEV((NB.NI_Newclose/LAG(NB.NI_Newclose,1) OVER(ORDER BY NB.NI_DATE)-1)*100)),
(((NB.NI_Newclose/LAG(NB.NI_Newclose,1) OVER(ORDER BY NB.NI_DATE)-1))*100-STDEV((NB.NI_Newclose/LAG(NB.NI_Newclose,1) OVER(ORDER BY NB.NI_DATE)-1)*100)),
(((NB.NI_Newclose/LAG(NB.NI_Newclose,1) OVER(ORDER BY NB.NI_DATE)-1))*100+2*(STDEV((NB.NI_Newclose/LAG(NB.NI_Newclose,1) OVER(ORDER BY NB.NI_DATE)-1))*100)),
(((NB.NI_Newclose/LAG(NB.NI_Newclose,1) OVER(ORDER BY NB.NI_DATE)-1))*100-2*(STDEV((NB.NI_Newclose/LAG(NB.NI_Newclose,1) OVER(ORDER BY NB.NI_DATE)-1))*100)),
(((NB.NI_Newclose/LAG(NB.NI_Newclose,1) OVER(ORDER BY NB.NI_DATE)-1))*100+3*(STDEV((NB.NI_Newclose/LAG(NB.NI_Newclose,1) OVER(ORDER BY NB.NI_DATE)-1))*100)),
(((NB.NI_Newclose/LAG(NB.NI_Newclose,1) OVER(ORDER BY NB.NI_DATE)-1))*100-3*(STDEV((NB.NI_Newclose/LAG(NB.NI_Newclose,1) OVER(ORDER BY NB.NI_DATE)-1))*100))


FROM
IndexAnalysis..NIFTY_50 NI
join
IndexAnalysis..NIFTYBANK NB
ON
NI.DATE= NB.NI_Date

SELECT
*
FROM
SUMMARY_RESULTS




